version: '3.9'

services: 
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    ports:
      - "5423:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: Qwe123
      PGDATA: /var/lib/postgresql/data/pgdata/
    volumes:
      - .:/var/lib/postgresql/data